import html2pdf from 'html2pdf.js';
import { Document, Packer, Paragraph, TextRun } from 'docx';

export async function exportPDF(element, { watermark, fileName='cv' } = {}) {
  // Tangkap ukuran asli preview (pixel) tanpa memaksa ke A4.
  const rect = element.getBoundingClientRect();
  const clone = element.cloneNode(true);
  // Bungkus agar tidak auto shrink dan menjaga layout persis seperti preview
  const container = document.createElement('div');
  container.style.width = rect.width + 'px';
  container.style.minHeight = rect.height + 'px';
  container.style.background = '#ffffff';
  container.style.margin = '0';
  container.style.padding = '0';
  container.style.boxSizing = 'border-box';
  container.appendChild(clone);
  if (watermark) {
    const wm = document.createElement('div');
    wm.textContent = 'Generated by CVin';
    wm.style.position = 'absolute';
    wm.style.bottom = '8px';
    wm.style.right = '12px';
    wm.style.fontSize = '10px';
    wm.style.opacity = '0.6';
    wm.style.fontFamily = 'Poppins, sans-serif';
    container.style.position = 'relative';
    container.appendChild(wm);
  }

  // Hitung ukuran dalam mm agar muat di satu halaman PDF.
  // Asumsi 96dpi (browser) -> 1 inch = 25.4mm
  const pxToMm = (px) => px * 25.4 / 96;
  const wMm = pxToMm(rect.width);
  const hMm = pxToMm(rect.height);

  // Tambahkan sedikit margin internal jika mau (0 agar presisi ke preview)
  const opt = {
    filename: fileName + '.pdf',
    margin: 0,
    image: { type: 'jpeg', quality: 0.96 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: [wMm, hMm], orientation: wMm > hMm ? 'landscape' : 'portrait' }
  };

  await html2pdf().from(container).set(opt).save();
}

export async function exportDOCX(data, { fileName='cv' } = {}) {
  const sections = [];
  const add = (title, value) => {
    if (!value) return;
    sections.push(new Paragraph({ children: [new TextRun({ text: title + ': ', bold: true }), new TextRun(value)] }));
  };
  add('Nama', data.name);
  add('Email', data.email);
  add('Telepon', data.phone);
  add('Ringkasan', data.summary);
  add('Pendidikan', data.education);
  add('Pengalaman', data.experience);
  add('Skill', data.skills);
  add('Sertifikasi', data.certifications);
  add('Bahasa', data.languages);

  const doc = new Document({ sections: [{ properties: {}, children: sections }] });
  const blob = await Packer.toBlob(doc);
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = fileName + '.docx';
  a.click();
  URL.revokeObjectURL(a.href);
}
